# Copyright 2022 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(
    name="main",
    entry_point="main.py",
)

python_tests(
    name="tests",
)
